[package]
name = "rust-app-template"
version = "0.1.0"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
edition = "2018"
build = "build.rs"
homepage = "https://github.com/Recmo/rust-app-template"
repository = "https://github.com/Recmo/rust-app-template"
description = "Template for running Rust in GKE"
readme = "Readme.md"

[features]
features = [ "bench" ]
bench = [ "criterion" ]

[lib]
path = "src/main.rs"

[[bench]]
name = "criterion"
harness = false
required-features = ["bench"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
criterion = { version = "0.3", optional = true }
futures = "0.3"
hyper = { version = "0.14", features = [ "full" ] }
itertools = "0.9"
num_cpus = "1.13"
once_cell = "1.5"
rand = "0.8"
rand_pcg = "0.3"
rayon = "1.5"
serde = "1.0"
smallvec = { version = "1.5", features = [ "serde" ] }
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1.0", features = [ "full" ] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"
tracing-test = "0.1"
tracing-timing = "0.4"

[dev-dependencies]
criterion = "0.3"
float_eq = "0.5"
pretty_assertions = "0.6"
proptest = "0.10"

[build-dependencies]
anyhow = "1.0"
chrono = "0.4"

# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3
